
version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  pull-and-build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy.sh"
workflows:
  flaskapp: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main
     
