
version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
<<<<<<< HEAD
          run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy.sh"
=======
          # app-dir: ~/project/package-directory/  # If you're requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
     

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
>>>>>>> refs/remotes/origin/main
workflows:
  flaskapp: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main
     
