version: 2.1
jobs: 
  run_tests:
    docker:
      - image: circleci/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 
            echo 'export PATH=~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install user -r requirements.txt
      - run:
          name: Run tests
          command: |
            pytest
      
workflows:
  build_and_test:
    jobs:
      - run_tests

    
